### ISSUE TITLE
Explore converting this away from dotnetcore

### ISSUE THREAD

**Issue by TemporalAgent7** [stt-datacore/image-analysis#1]
This project is an older implementation of the bot that is currently only used for the image analysis part. Explore options for moving away from dotnetcore:

- embed the functionality as a node module or rewrite it using existing node modules
- write a simple C++ program that links with opencv and provides just the functionality needed for behold / voyage screen image recognition

Note that looking at existing opencv node.js bindings, most are missing some needed functionality (either the SURF descriptor, or the functionality of Flann matching across all crew matrices - see [here](https://github.com/stt-datacore/image-analysis/blob/26869f576002b7b33c42fa09b0d124ae4c808515/src/DataCore.Library/AIMagic/Searcher.cs#L178) ).

**Comment by ineffyble** [comment]
@TemporalAgent7 This is done and implemented in https://github.com/stt-datacore/cpp-image-analysis right?

**Comment by TemporalAgent7** [comment]
Yes, this is the old / deprecated image analysis written in dotnetcore; we successfully transitioned away from it about 6 months ago. We can archive the project (there's some pieces that may be interesting for future archeologists of datacore, such as the deprecated reddit bot).
